# Generated by Django 5.0.3 on 2024-03-16 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_ticket_user_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='actors',
            table='Actor',
        ),
    ]
