# Generated by Django 5.0.3 on 2024-03-16 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_actors_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='actors',
            table=None,
        ),
    ]
